### ISSUE TITLE
The script will not select the last item in a collection.

### ISSUE THREAD

**Issue by adam-s** [larryprice/mongoose-simple-random#5]
I have a collection with 10 documents. This will only select one of the first 9 randomly. Or, 100 documents and it will only select one of the first 99.

      var start = Math.max(0, Math.floor((num-limit)*Math.random()));

might be written as 

      var start = Math.max(0, Math.floor(((num-limit)+1)*Math.random()));

I didn't test.

**Comment by larryprice** [comment]
I agree! I'll write up some code to fix this. Thanks for adding the issue.

**Comment by larryprice** [comment]
Fixed by b687ad8

Thanks!

**Comment by larryprice** [comment]
As a note, this is live as of version 0.3.1 of the package on npm.
